stubrunner:
  cloud.stubbed.discovery.enabled: false
  repositoryRoot: ${REPO_WITH_JARS:http://localhost:8081/artifactory/libs-release-local}
server.port: ${PORT:8083}
spring:
  cloud.stream.defaultBinder: rabbit
  application:
    name: stubrunner